apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: demo
  labels:
    app: web-app
    platform: python
spec:
  replicas:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
            #      imagePullSecrets:
            #      - name: docker-private-registry-key
      containers:
      - name: web-app
        image: sreejithvu/email-jun17:first
        #        imagePullPolicy: Always
        ports:
- containerPort: 5000
